name: Ejecutar prueba automatizada y actualizar Jira

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * 1 1' # Programado para ejecutarse todos los días a medianoche

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar prueba y actualizar Jira
      run: |
        python main_update.py

    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_URL: ${{ secrets.JIRA_URL }}
